---
stages:
- name: Empty Build Stage
  inputs:
  - type: git
    branch: master
  jobs:
  - name: Empty Build Job
    type: builder
- name: Deploy to Bluemix
  inputs:
  - type: job
    stage: Empty Build Stage
    job: Empty Build Job
  triggers:
  - type: stage
  jobs:
  - name: Push to Cloud Foundry
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
blockchainService='BlockchainExampleServiceHfc'
appNames=`cf apps`
regex='BlockchainExampleHfc*'
routeName='mybluemix.net$'
appToUnbind=''
for app in $appNames;
do
	if [[ $app =~ $routeName ]]
	then
		continue
	fi
	if [[ $app =~ $regex ]]
	then
		appToUnbind=$app
		echo $appToUnbind
	fi
done
cf us $appToUnbind $blockchainService
cf delete-service $blockchainService -f
cf create-service ibm-blockchain-5-prod ibm-blockchain-plan-5-prod $blockchainService
cf push "${CF_APP}"
